package dev.sort.duckdb.tools

import java.io.File
import java.sql.Connection
import java.sql.DriverManager

/**
 * Extension→functions harvester (sibling to FunctionCatalogHarvest): captures the function names
 * each curated DuckDB extension ADDS, by diffing duckdb_functions() across INSTALL+LOAD on a
 * fresh in-process connection, and writes them as a plugin resource —
 *  - extension-functions.tsv: name<TAB>kind<TAB>extension (kind = raw duckdb function_type),
 *    deduped per extension, sorted by extension then name, with a provenance header.
 *
 * INSTALL pulls from the DuckDB extension repository (network required). Each extension gets its
 * OWN fresh `jdbc:duckdb:` :memory: connection so loads never contaminate one another; any
 * INSTALL/LOAD failure is caught and the extension SKIPPED (warned) so one unreachable extension
 * can't kill the run. Statically-linked extensions already present on a fresh connection are
 * LOAD-only (INSTALL would error) and, adding nothing over baseline, are noted as autoloaded.
 * The map holds ONLY extension-added names — asserted against the base functions.tsv before
 * writing (fails loudly on any overlap).
 *
 * Deterministic output; re-run on every duckdb_jdbc bump and commit the diff.
 * Usage: ExtensionCatalogHarvest <resourceDir>   (the dir that also holds functions.tsv)
 */
fun main(args: Array<String>) {
    val outDir = File(args[0]).apply { mkdirs() }
    val baseFile = File(outDir, "functions.tsv")
    require(baseFile.isFile) { "base catalog missing (run harvestFunctionCatalog first): $baseFile" }
    val baseNames = baseFile.readLines()
        .filter { it.isNotBlank() && !it.startsWith("#") }
        .map { it.substringBefore('\t') }
        .toSet()

    val extensions = listOf("httpfs", "spatial", "fts", "icu", "inet", "sqlite_scanner", "postgres_scanner")
    val rows = sortedMapOf<Pair<String, String>, String>(compareBy({ it.first }, { it.second })) // (ext, name) -> kind
    val counts = LinkedHashMap<String, Int>()      // ext -> added count
    val skipped = LinkedHashMap<String, String>()  // ext -> first-line failure reason
    val autoloaded = ArrayList<String>()           // already loaded on a fresh connection (functions in baseline)
    val noFunctions = ArrayList<String>()          // loaded fresh but registers no duckdb_functions() entries

    var engineVersion = "unknown"
    DriverManager.getConnection("jdbc:duckdb:").use { c ->
        c.createStatement().executeQuery("SELECT version()").use { rs -> if (rs.next()) engineVersion = rs.getString(1) }
    }
    println("extension harvest: engine $engineVersion")

    for (ext in extensions) {
        try {
            // Fresh :memory: instance per extension — loads never contaminate the next diff.
            DriverManager.getConnection("jdbc:duckdb:").use { c ->
                val baselineLoaded = extensionLoaded(c, ext)
                val baseline = functionTypes(c).keys
                c.createStatement().use { st ->
                    // Statically-linked/built-in extensions are already present; INSTALL would error,
                    // LOAD is a no-op. Only reach out to the repo when the fresh connection lacks it.
                    if (!baselineLoaded) st.execute("INSTALL $ext;")
                    st.execute("LOAD $ext;")
                }
                val after = functionTypes(c)
                val added = after.keys - baseline
                counts[ext] = added.size
                for (name in added) rows.putIfAbsent(ext to name, after.getValue(name))
                when {
                    added.isNotEmpty() -> println("  $ext: +${added.size} functions")
                    baselineLoaded -> {
                        autoloaded += ext
                        println("  $ext: +0 (autoloaded in-process — its functions are already in functions.tsv)")
                    }
                    else -> {
                        noFunctions += ext
                        println("  $ext: +0 (loaded, registers no duckdb_functions() entries)")
                    }
                }
            }
        } catch (e: Exception) {
            val reason = (e.message ?: e.javaClass.simpleName).lineSequence().first().trim().take(160)
            skipped[ext] = reason
            println("  WARNING: skipping $ext — $reason")
        }
    }

    // The map holds extension-added names ONLY; a leak here means a stale baseline or an autoload
    // the diff missed. Fail loudly rather than shipping a base name mislabelled as extension-owned.
    val leaked = rows.keys.map { it.second }.filter { it in baseNames }.toSortedSet()
    check(leaked.isEmpty()) { "extension map leaked ${leaked.size} base-catalog name(s): $leaked" }

    val header = buildString {
        appendLine("# DuckDB extension→functions map — generated by harvestExtensionCatalog (ExtensionCatalogHarvest.kt)")
        appendLine("# engine: $engineVersion")
        appendLine("# extensions attempted: ${extensions.joinToString(", ")}")
        appendLine("# skipped (install/load failed): ${skipped.keys.joinToStringOrNone()}")
        appendLine("# autoloaded in-process (functions already in functions.tsv): ${autoloaded.joinToStringOrNone()}")
        appendLine("# loaded but adds no duckdb_functions() entries: ${noFunctions.joinToStringOrNone()}")
        appendLine("# columns: name<TAB>kind<TAB>extension  (kind = raw duckdb function_type; extension-added names only)")
    }
    val body = rows.entries.joinToString("\n") { (key, kind) -> "${key.second}\t$kind\t${key.first}" }
    val outFile = File(outDir, "extension-functions.tsv")
    outFile.writeText(header + body + "\n")

    println(
        "extension map: ${rows.size} rows across ${counts.count { it.value > 0 }} contributing extension(s)" +
            (if (skipped.isEmpty()) "" else ", ${skipped.size} skipped") +
            ", no-overlap assert PASSED -> $outFile",
    )
}

private fun functionTypes(c: Connection): Map<String, String> {
    val out = LinkedHashMap<String, String>()
    c.createStatement().executeQuery(
        // Matches FunctionCatalogHarvest: DISTINCT (name, type), first type per name by (name, type).
        "SELECT DISTINCT function_name, function_type FROM duckdb_functions() ORDER BY 1, 2",
    ).use { rs ->
        while (rs.next()) out.putIfAbsent(rs.getString(1), rs.getString(2))
    }
    return out
}

private fun extensionLoaded(c: Connection, ext: String): Boolean =
    c.prepareStatement("SELECT loaded FROM duckdb_extensions() WHERE extension_name = ?").use { ps ->
        ps.setString(1, ext)
        ps.executeQuery().use { rs -> rs.next() && rs.getBoolean(1) }
    }

private fun Collection<String>.joinToStringOrNone(): String = if (isEmpty()) "none" else joinToString(", ")
